package media

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"math"
	"net/http"
	"strings"
	"time"

	"github.com/hajimehoshi/go-mp3"
	esphome "github.com/ygelfand/go-esphome-device"

	"github.com/HuskerMinion/techo5/echod/internal/hardware/speaker"
)

// Formats is what Home Assistant is asked to convert to. It runs the conversion through ffmpeg, so
// asking for plain WAV means no decoder here: strip the header and the rest is samples.
//
// Music gets the codec's own rate and both channels, so nothing is resampled and nothing is thrown
// away. Announcements stay at the pipeline's rate: they are one voice, and the bandwidth would buy
// nothing but a longer wait before the device says anything.
var Formats = []esphome.MediaFormat{
	{Format: "wav", SampleRate: speaker.Rate, Channels: speaker.Channels, SampleBytes: 2},
	{Format: "wav", SampleRate: speaker.VoiceRate, Channels: 1, SampleBytes: 2, Announcement: true},
}

// Tail is the silence added after speech, in milliseconds. Speech generated by a text to speech
// engine stops on its last sound with no silence after it, and the interpolating resampler needs a
// few samples beyond the end to run out. Without a tail the final word sounds cut off.
const Tail = 250

const fetchTimeout = 30 * time.Second

// mostAudio is how much of a body will be read. An announcement is a doorbell chime or a sentence of
// speech, and the widest thing Home Assistant converts to is 16-bit stereo at the card's 48 kHz, so
// this is a couple of minutes of the largest form anything here arrives in. What it guards against is
// the other end never stopping: the url is whatever Home Assistant handed over, which for an external
// media source is a host nobody here controls, and the whole body is held in memory and decoded into
// samples held beside it. A device with half a gigabyte does not survive a stream that goes on.
const mostAudio = 2 * 60 * speaker.Rate * speaker.Channels * 2

// Fetch downloads audio Home Assistant is serving and decodes it. The request carries the context, so
// silencing a sound abandons the download rather than leaving it to arrive and be thrown away.
func Fetch(ctx context.Context, url string) ([]int16, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, errors.New("audio request is invalid")
	}

	client := &http.Client{Timeout: fetchTimeout}
	resp, err := client.Do(req)
	if err != nil {
		return nil, errors.New("audio request failed")
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("audio server returned %s", resp.Status)
	}

	// One byte past the bound, so a body that is exactly at it still plays and anything larger is
	// refused by name rather than played half way through.
	body, err := io.ReadAll(io.LimitReader(resp.Body, mostAudio+1))
	if err != nil {
		return nil, err
	}
	if len(body) > mostAudio {
		return nil, fmt.Errorf("more than %d bytes of audio for one announcement", mostAudio)
	}
	var (
		samples []int16
		f       wavFormat
	)
	switch {
	case len(body) >= 12 && string(body[0:4]) == "RIFF":
		samples, f, err = monoPCM(body)
	case isMP3(body, resp.Header.Get("Content-Type")):
		samples, f, err = monoMP3(body)
	default:
		head := body
		if len(head) > 4 {
			head = head[:4]
		}
		err = fmt.Errorf("unrecognised audio: %d bytes, content-type %q, starts %q", len(body), resp.Header.Get("Content-Type"), string(head))
	}
	if err != nil {
		return nil, err
	}
	if f.channels != 1 || f.rate != speaker.VoiceRate {
		slog.Info("announcement converted", "from", fmt.Sprintf("%d Hz, %d ch, %s", f.rate, f.channels, f.codec))
	}
	return samples, nil
}

// Speech loudness. Text-to-speech engines deliver quiet files — Piper peaks around -12 dBFS and
// sits far lower on average — and a speaker played at unity is then heard as "medium" with the
// dial at the top. Announcements are whole clips, so their level can be measured before anything
// plays, and each is brought to the same RMS target with peaks soft-limited. The dial scales from
// there.
const (
	// speechTargetRMS is the level speech is normalized to, as a fraction of full scale (-18 dBFS).
	speechTargetRMS = 0.126
	// speechMaxGain caps how far a very quiet clip is lifted, so silence and noise are not amplified
	// without limit (+18 dB).
	speechMaxGain = 8.0
	// speechKnee is where the peak limiter starts to compress, as a fraction of full scale.
	speechKnee = 0.8
)

// Normalize brings a speech clip to speechTargetRMS with soft-limited peaks. A clip already at or
// above the target is returned unchanged.
func Normalize(in []int16) []int16 {
	gain := SpeechGain(SumSquares(in), len(in))
	if gain <= 1 {
		return in
	}
	return Scale(in, gain)
}

// SumSquares is the energy of a clip at full-scale units, for SpeechGain. Streamed speech
// accumulates it chunk by chunk.
func SumSquares(in []int16) float64 {
	var sum float64
	for _, s := range in {
		v := float64(s) / 32768
		sum += v * v
	}
	return sum
}

// SpeechGain is the gain that brings audio of the given energy and length to speechTargetRMS,
// between 1 (never quieter) and speechMaxGain.
func SpeechGain(sumSquares float64, n int) float64 {
	if n == 0 || sumSquares <= 0 {
		return 1
	}
	rms := math.Sqrt(sumSquares / float64(n))
	gain := speechTargetRMS / rms
	if gain <= 1 {
		return 1
	}
	return math.Min(gain, speechMaxGain)
}

// Scale multiplies samples by gain with a soft peak limiter: linear to speechKnee, then the
// remaining headroom is approached asymptotically, so a loud syllable compresses rather than cracks.
func Scale(in []int16, gain float64) []int16 {
	out := make([]int16, len(in))
	const knee = speechKnee * 32767
	const headroom = 32767 - knee
	for i, s := range in {
		v := float64(s) * gain
		a := math.Abs(v)
		if a > knee {
			over := a - knee
			a = knee + headroom*over/(over+headroom)
			if v < 0 {
				v = -a
			} else {
				v = a
			}
		}
		out[i] = int16(v)
	}
	return out
}

// isMP3 recognizes what Home Assistant's tts_proxy serves when it does not convert: an MP3, with
// or without an ID3 tag in front.
func isMP3(body []byte, contentType string) bool {
	if strings.HasPrefix(contentType, "audio/mpeg") || strings.HasPrefix(contentType, "audio/mp3") {
		return true
	}
	if len(body) >= 3 && string(body[:3]) == "ID3" {
		return true
	}
	return len(body) >= 2 && body[0] == 0xFF && body[1]&0xE0 == 0xE0
}

// monoMP3 decodes an MP3 to one channel at speaker.VoiceRate. go-mp3 always yields 16-bit stereo at
// the file's rate.
func monoMP3(body []byte) ([]int16, wavFormat, error) {
	f := wavFormat{channels: 2, bits: 16, codec: "mp3"}
	d, err := mp3.NewDecoder(bytes.NewReader(body))
	if err != nil {
		return nil, f, fmt.Errorf("mp3: %w", err)
	}
	f.rate = d.SampleRate()
	// The same bound as the body, on what it decodes to: a few megabytes of MP3 are many more of
	// samples, and go-mp3 always gives 16-bit stereo, which is the form mostAudio is counted in.
	pcm, err := io.ReadAll(io.LimitReader(d, mostAudio+1))
	if err != nil {
		return nil, f, fmt.Errorf("mp3: %w", err)
	}
	if len(pcm) > mostAudio {
		return nil, f, fmt.Errorf("mp3: more than %d bytes of samples for one announcement", mostAudio)
	}
	frames := len(pcm) / 4
	mono := make([]int16, frames)
	for i := range mono {
		l := int(int16(binary.LittleEndian.Uint16(pcm[i*4:])))
		r := int(int16(binary.LittleEndian.Uint16(pcm[i*4+2:])))
		mono[i] = int16((l + r) / 2)
	}
	return toVoiceRate(mono, f.rate), f, nil
}

// wavFormat is what the container said about the audio.
type wavFormat struct {
	channels, rate, bits int
	codec                string
}

// monoPCM takes 16-bit samples out of a RIFF/WAVE body, walking the chunks rather than assuming a
// 44-byte header: a converted file can carry extra chunks before the data. The result is one channel
// at speaker.VoiceRate whatever the file carried: Home Assistant is asked for that, but what it
// serves is decided by its proxy, and a mismatch played as if it were right is speech at the wrong
// speed.
//
// Sizes are handled as uint64. A 32-bit int cannot hold a large RIFF size, and a chunk claiming
// one turns negative, which slips past a bounds check and panics on the slice.
func monoPCM(body []byte) ([]int16, wavFormat, error) {
	f := wavFormat{channels: 1, rate: speaker.VoiceRate, bits: 16, codec: "wav"}
	if len(body) < 12 || string(body[0:4]) != "RIFF" || string(body[8:12]) != "WAVE" {
		return nil, f, fmt.Errorf("not a WAVE file: %d bytes", len(body))
	}

	total := uint64(len(body))
	for off := uint64(12); off+8 <= total; {
		id := string(body[off : off+4])
		size := uint64(binary.LittleEndian.Uint32(body[off+4 : off+8]))
		off += 8

		end := off + size
		if end > total {
			end = total
		}

		switch id {
		case "fmt ":
			if end-off >= 16 {
				f.channels = int(binary.LittleEndian.Uint16(body[off+2:]))
				f.rate = int(binary.LittleEndian.Uint32(body[off+4:]))
				f.bits = int(binary.LittleEndian.Uint16(body[off+14:]))
			}
		case "data":
			if f.bits != 16 || f.channels < 1 {
				return nil, f, fmt.Errorf("unsupported WAVE: %d-bit, %d channels", f.bits, f.channels)
			}
			pcm := body[off:end]
			frames := len(pcm) / (2 * f.channels)
			mono := make([]int16, frames)
			for i := range mono {
				var sum int
				for c := 0; c < f.channels; c++ {
					sum += int(int16(binary.LittleEndian.Uint16(pcm[(i*f.channels+c)*2:])))
				}
				mono[i] = int16(sum / f.channels)
			}
			return toVoiceRate(mono, f.rate), f, nil
		}

		off = end
		if size%2 == 1 {
			off++
		}
	}
	return nil, f, fmt.Errorf("no data chunk in %d bytes", total)
}

// ToVoiceRate is toVoiceRate, for speech that arrives some other way than a URL.
func ToVoiceRate(in []int16, rate int) []int16 { return toVoiceRate(in, rate) }

// toVoiceRate brings mono speech to speaker.VoiceRate by linear interpolation, which is plenty for
// a voice that is about to be upsampled again on the way to the card.
func toVoiceRate(in []int16, rate int) []int16 {
	if rate == speaker.VoiceRate || rate <= 0 || len(in) < 2 {
		return in
	}
	n := int(int64(len(in)) * int64(speaker.VoiceRate) / int64(rate))
	out := make([]int16, n)
	step := float64(rate) / float64(speaker.VoiceRate)
	for i := range out {
		pos := float64(i) * step
		j := int(pos)
		if j >= len(in)-1 {
			out[i] = in[len(in)-1]
			continue
		}
		frac := pos - float64(j)
		out[i] = int16(float64(in[j])*(1-frac) + float64(in[j+1])*frac)
	}
	return out
}
